import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Adzat Interviewer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <nav className="w-full bg-[#1a1a1a] p-4 rounded-md shadow-lg flex items-center justify-between">
          <div className="text-lg font-bold text-white">Adzat.io Interview</div>
          <ul className="flex space-x-6">
            <li><a href="#" className="text-gray-300 hover:text-white transition-colors duration-200">Home</a></li>
            <li><a href="#" className="text-gray-300 hover:text-white transition-colors duration-200">About</a></li>
            <li><a href="#" className="text-gray-300 hover:text-white transition-colors duration-200">Contact</a></li>
          </ul>
        </nav>

        <div className="flex-1 flex flex-col items-center justify-center bg-[#0e0e0e] text-white px-4">
          {children}
        </div>

        <footer className="w-full bg-[#1a1a1a] p-3 text-center text-gray-400 text-sm rounded-md shadow-lg">
          © {new Date().getFullYear()} Adzat.io. All rights reserved. Licensing information available upon request.
        </footer>
      </body>
    </html>
  );
}
