import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Adzat Interviewer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen h-full m-0`}
      >
        <nav className="w-full bg-white p-4 shadow-sm flex items-center justify-between sticky top-0 z-10">
          <div className="text-lg font-bold text-indigo-600">Adzat.io Interview</div>
          {/* <ul className="flex space-x-6">
            <li><a href="/" className="text-gray-600 hover:text-indigo-600 transition-colors duration-200">Home</a></li>
            <li><a href="/about" className="text-gray-600 hover:text-indigo-600 transition-colors duration-200">About</a></li>
            <li><a href="/contact" className="text-gray-600 hover:text-indigo-600 transition-colors duration-200">Contact</a></li>
          </ul> */}
        </nav>

        <main className="flex-grow flex flex-col bg-gradient-to-b from-gray-100 to-gray-200 py-8">
          {children}
        </main>

        <footer className="w-full bg-white p-3 text-center text-gray-500 text-sm shadow-sm relative z-10">
          © {new Date().getFullYear()} Adzat.io. All rights reserved.
        </footer>
      </body>
    </html>
  );
}
